### PR TITLE
Update eglQueryAPI.xml

### PR DESCRIPTION
**Pull request by rpavlik**
Fix an apparent typo: this is the only revision that made sense to me.

### CODE REVIEW

**Review by stonesthrow — COMMENTED** [review]
Agreed, the first part of the note matches section 3.7 of spec. The "however" clause makes sense in that its invalid to use with eglBindAPI, and this is consistent with the rest of the text here under "eglQueryAPI".

**Comment by stonesthrow** [comment]
@oddhack , please check this typo.

**Comment by oddhack** [comment]
LGTM. You can set Approved to Merge or just merge it (I'll have to regenerate the HTML refpages though, so probably best if I merge it).

**Comment by oddhack** [comment]
Page regenerated.

**Pull request merged**
