### PR TITLE
Move QNX EGL native types block (#191)

### PR DESCRIPTION
**Pull request by jmcdonnell-blackberry**

### CODE REVIEW

**Review by stonesthrow — APPROVED** [review]
Looks fine to me.

**Comment by stonesthrow** [comment]
Closes #191

**Review by oddhack — APPROVED** [review]
LGTM. Though it might be helpful to run this by Mesa as they are exposed to a wide range of platforms.

**Comment by stonesthrow** [comment]
@versalinyaa , Lina do you have time for a quick review of this change to eglPlatform.h on behave of the MESA community?

**Review by cubanismo — APPROVED** [review]
Looks good to me. I ran this by our embedded team as well, and they have no objections.

**Comment by versalinyaa** [comment]
It's already been merged, but still lgtm.

**Comment by stonesthrow** [comment]
We pulled the trigger and merged. thanks

**Pull request merged**
