### PR TITLE
Add EGL 1.5 reference pages, and additions to existing reference pages.

### PR DESCRIPTION
**Pull request by oddhack**
This is based on the initial EGL 1.5 release of March 12, 2014. There
have been a couple of minor updates to the 1.5 Specification since then,
which will need to be reflected in these pages, but they should be
substantially complete.

### CODE REVIEW

**Comment by 1ace** [comment]
I haven't read everything, but I've glanced through and read a few bits, and didn't see anything wrong.
I have also tested that the [man pages](https://aur.archlinux.org/packages/egl-man-pages) still compile fine :)

**Comment by stonesthrow** [comment]
I cloned the branch locally and looked in the man directory and opened the new (just new functions) .xhtml, and .html files
1. .html files are generated to xhtml folder, and .xhtml files are generated to html folder.
2. I don't see *.html files for the new functions
3. The *.xhtml files for eglCreatePlatform*Surface, don't look like they were generated.
4. eglGetSyncAttrib, "parameters" section has "flag and timeout" instead of "attribute and value"
5. eglCreateImage, section attrib_list typo with "sub-sectin"
6. eglDestroyImage, section parameters has "sync" instead of "image"

**Comment by oddhack** [comment]
The xhtml/ directory contains old pages generated from Docbook4 sources. It only exists to avoid dead links on the website - the html/ directory is what's linked from the registry. The suffix inconsistency is an unfortunate artifact of the switchover from Docbook 4 -> 5 source format.

Ideally someday all the docbook format ref pages can be converted to asciidoctor format, but that's a lot of tedious infrastructure work.

I believe all the other issues have been dealt with - thanks!

**Comment by stonesthrow** [comment]
The update commit seems to have all the fixes. Thanks. I'm away from my local repo and when back this weekend I'll pull the latest and proof read the page text in html.

**Comment by stonesthrow** [comment]
7. eglCreateImage - in parameters "sync" should be "Context"
8. eglCreatePlatfromPixmapSurface is not generated.

**Comment by stonesthrow** [comment]
+1

**Comment by stonesthrow** [comment]
Remove from eglChooseConfig the text that EGL_ALPHA_MASK_SIZE is for OpenGL, change to associated with OpenVG.
per isse: https://github.com/KhronosGroup/EGL-Registry/issues/62

**Comment by oddhack** [comment]
@stonesthrow the reference pages are backed from this repository, so as soon as khronos.org pulled it after accepting the MR, they were visible. No additional help needed.

**Pull request merged**
