### PR TITLE
Const-qualify attrib_list in eglStreamConsumerGLTextureExternalAttrib…

### PR DESCRIPTION
**Pull request by jdashg**
…sNV.

### CODE REVIEW

**Comment by jdashg** [comment]
We ran into this while using the extension for sampling from d3d11 textures in ANGLE.

**Comment by oddhack** [comment]
@jdashg please add the matching change to egl.xml, and I'll accept this. Thanks.

**Comment by jdashg** [comment]
@oddhack I updated the xml and regenerated the headers.

**Comment by jdashg** [comment]
Rebased on master.

**Pull request merged**
